### ISSUE TITLE
Não consegui executar o playbook

### ISSUE THREAD

**Issue by deoogo** [Roberto-seg/Teste-Base-Mandic-Roberto-segundo#1]
Roberto.

[root@localhost ansible]# ansible-playbook -i hosts setup.yml 

PLAY [Setup] *****************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
fatal: [192.168.1.4]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.4 port 22: Connection timed out", "unreachable": true}

PLAY RECAP *******************************************************************************************************************************************
192.168.1.4                : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

[root@localhost ansible]# vi hosts
[root@localhost ansible]# ansible-playbook -i hosts setup.yml 
[WARNING]: Could not match supplied host pattern, ignoring: 192.168.1.4

PLAY [Setup] *****************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *******************************************************************************************************************************************

[root@localhost ansible]# 

**Como eu rodo o seu playbook é importante q seja em localhost;**

**Comment by Roberto-seg** [comment]
Olá Diogo tudo bem? configurei o ansible para fazer o provisionamento via localhost

**Comment by Roberto-seg** [comment]
playbook atualizada
